### PR TITLE
Add coveralls coverage report from Travis CI

### PR DESCRIPTION
**Pull request by fubuloubu**
### - What I did
This should hopefully add coveralls integration to Travis CI so that we can get a coverage badge.

### - How to verify it
Travis CI will run and hopefully not fail, and then we can add a coverage badge

### - Cute Animal Picture
Baby turtle

### CODE REVIEW

**Comment by fubuloubu** [comment]
@DavidKnott or someone with Write access and an account on Travis CI may have to follow from step 5 [here](https://www.gregjs.com/javascript/2016/how-to-get-a-shiny-coverage-badge-for-your-github-project/)

**Comment by DavidKnott** [comment]
@fubuloubu Thanks for getting this started.   I've enabled coveralls, can you add the badge to your PR?
Here it is:
```
[![Coverage Status](https://coveralls.io/repos/github/ethereum/viper/badge.svg?branch=master)](https://coveralls.io/github/ethereum/viper?branch=master)
```

**Comment by fubuloubu** [comment]
Added badge and merged. Not sure if the badge is working though.

**Comment by JackieXu** [comment]
Badge appears fine, but we don't have any jobs within `coveralls` yet, it seems. I don't have any experience with `coveralls` myself, can we make it listen on PRs?

**Comment by fubuloubu** [comment]
If it's easy, I agree. But code coverage data is more useful for the main branch than any PR anyways.

**Comment by JackieXu** [comment]
Agreed, should have added 'on merge', because I think that's the only way to add code to the `master` branch.

Else something that triggers on any change to the `master` branch would be great.

**Comment by DavidKnott** [comment]
Hmm, in the travis build it says:
     
     $ coveralls
     coveralls: command not found
Is that just because it's not in master?

**Comment by fubuloubu** [comment]
I have no idea, that was my thought. Or like, something has to be enabled.

**Comment by JackieXu** [comment]
You're missing a `pip install coveralls` in the `.travis.yml`. It won't have the executable otherwise.

**Comment by fubuloubu** [comment]
@JackieXu thanks! I knew I was missing something :)

**Comment by fubuloubu** [comment]
Woot, it works!

**Comment by JackieXu** [comment]
Excellent! Some minor nitpicking: could you rebase the branch instead of using the merge commit? 
I also think it would look a bit neater if you could squash [`566cde6036a4a7e250bc7bf4ead263261cf39096`](https://github.com/ethereum/viper/pull/343/commits/566cde6036a4a7e250bc7bf4ead263261cf39096) and [`cd765e104c02e67cc3c62fe6624ac1a34ee3b876`](https://github.com/ethereum/viper/pull/343/commits/cd765e104c02e67cc3c62fe6624ac1a34ee3b876) together.

**Comment by fubuloubu** [comment]
@DavidKnott there's a configuration in Travis/coveralls to have it not comment on PR's

**Comment by fubuloubu** [comment]
@JackieXu do you have a guide or instructions on how best to do that in GitHub? The last time I tried I really screwed up the PR in GitHub. I wish it would just recognize the rebase instead of pretending all the commits in the mean time were mine

**Comment by JackieXu** [comment]
@fubuloubu Do you mean the GitHub client? I'm not sure; I can guide you through a 'regular' Git way of fixing it, though.

An important thing to note, is the merge commit you have: `80c0d1f1378ff54ca311a9b393a9a93f5ef28737`. Ideally you would like to avoid these in PRs (unless you somehow have people making PRs on your fork that are required for PRs on the source repository, but that can get really complicated really fast, so let's ignore those for a while).

Let's do this a 'clean' way, and go back to the point where you diverged from the source `master` branch: the commit *before* your merge commit: `a494d3edd95aef10d52d54b2835ab1b1aa98a317`.

There's an easy way to return there, without losing any of your changes, but it does remove the commits that happened in between then and now:
`git reset --soft a494d3edd95aef10d52d54b2835ab1b1aa98a317`

This will put you at a point in time right after your first documentation badge PR was merged in, with two changed files:
- `.travis.yml`
- `README.md`

Now, by default, these will already be tracked by `git`, so let's start from a 'clean' position by unstaging them using:
`git reset HEAD .`

This will move all files from the current working directory and its subdirectories to an unstaged state.

From here on you can add them separately in two commits, or bundle them in a single commit. If you want to keep in line with your current commit messages, you would do something like this:
- `git add .travis.yml && git commit -m "Add coveralls coverage report from Travis CI"`
- `git add README.md && git commit -m "Added Code Coverage Badge"`

At this point, you will have your commits on top of state as it was yesterday. To get things properly rebased you can fetch the changes from the source repository (I will assume you registered it as `upstream`, but otherwise replace it with what it's called in your configuration):
- `git fetch upstream`
- `git rebase upstream/master`

And now you are entirely up-to-date with your commits safely rebased on top of the source branch. To push it to your own branch (and I'm assuming you called your own repository `origin`), you will have to do some forcing, though:
`git push origin patch-2 --force`

**Comment by fubuloubu** [comment]
Ah, I think my problem is that I was rebasing on my local `master` instead of `upstream/master`. Thanks for the tip! I'll give that a shot.

**Comment by JackieXu** [comment]
Common mistake that I've made quite a few times mysql! GitHub has no way to keep a fork in sync, which means you have to do this manually. This can be a surprise if you don't expect it. 😄

**Comment by fubuloubu** [comment]
Awesome, all fixed!

**Comment by DavidKnott** [comment]
Great job getting it working!

**Comment by DavidKnott** [comment]
Nice job getting it work, I turned off the comments.

**Comment by DavidKnott** [comment]
Merging it in.

**Pull request merged**
