### PR TITLE
Storage list logging

### LINKED ISSUE #551: Fix: Support for logging lists from storage
### What's your issue about?
Currently code that retrieves a list from storage and echoes it out to a log statement throws a compile error.
```python
Bar: __log__({_value: num[4]})
x: num[4]

@public
def foo():
    log.Bar(self.x)
```

### How can it be fixed?

Check `pack_args_by_32` function and add support for it :smile: 

Thanks goes out to @yzhang90 for finding it.

### PR DESCRIPTION
**Pull request by jacqueswww**
### - What I did
Fixes #551.

- Adds support for logging lists from storage.
- Adds support for logging lists from storage. 
- Tests.

### - How I did it

See pack_args_by_32.

### - How to verify it

See #551.

```python
Bar: __log__({_value: num[4]})
x: num[4]

@public
def foo():
    log.Bar(self.x)

@public
def set_list():
    self.x = [1, 2, 3, 4]
```

```python
MyLog: __log__({arg1: bytes <= 29})
x:bytes<=5

@public
def foo(a:num):
    log.MyLog(self.x)

@public
def setbytez():
    self.x = 'hello'

@public
def getbytes() -> bytes <=29:
    return self.x

```

### CODE REVIEW

**Comment by fubuloubu** [comment]
Testing looks good to me

**Comment by DavidKnott** [comment]
@jacqueswww Could add test logging a list of a different type?

**Comment by jacqueswww** [comment]
@DavidKnott sure thing will do.

**Comment by jacqueswww** [comment]
@DavidKnott done :)

**Comment by DavidKnott** [comment]
@jacqueswww Thanks, LGTM

**Pull request merged**
