### PR TITLE
Updates to function name and signature in ABI

### LINKED ISSUE #344: Remove inputs from abi name field.
### What's your issue about?
Viper's abi `name` field should not have a functions inputs attached to it for two reasons:
1) Duplicate information (the inputs are already in that abi elsewhere)
2) Abi uniformity, now the `name` field will match Solidity's

### How can it be fixed?

Change abi `name` to not have inputs

#### Cute Animal Picture

image

### PR DESCRIPTION
**Pull request by fubuloubu**
### - What I did
Update to function signature to have name be function name, added signature field to abi, fixed abi signature field to reflect return type as well. Fixes #344

### - Description for the changelog
ABI Change

### - Cute Animal Picture

baby walrus

### CODE REVIEW

**Comment by fubuloubu** [comment]
Welp, I should've checked that. Apparently it was being used for gas estimation somehow in the tests...

**Comment by fubuloubu** [comment]
@DavidKnott it passes now, but `sig.name` is used in a lot of suspect places in `parser.py`, I think as a proxy for determining uniqueness, so the meaning might have changed for it's usage.

**Comment by fubuloubu** [comment]
I highlighted a few potential problem areas...

```diff
diff --git a/viper/parser.py b/viper/parser.py
index 623e035..dd986b6 100644
--- a/viper/parser.py
+++ b/viper/parser.py
@@ -238,6 +238,7 @@ def parse_tree_to_lll(code, origcode):
             add_gas += 30
             sig = FunctionSignature.from_definition(_def)
             sig.gas = sub[-1].total_gas
+            #Problem?
             sigs[sig.name] = sig
         o.append(['return', 0, ['lll', sub, 0]])
     return LLLnode.from_list(o, typ=None)
@@ -285,6 +286,7 @@ def parse_func(code, _globals, sigs, origcode, _vars={}):
         if arg.name in _globals:
             raise VariableDeclarationException("Variable name duplicated between function arguments and globals: "+arg.name)
     # Create a context
+    #Problem?
     context = Context(vars=_vars, globals=_globals, sigs=sigs,
                       return_type=sig.output_type, is_constant=sig.const, is_payable=sig.payable, origcode=origcode)
     # Copy calldata to memory for fixed-size arguments
@@ -293,6 +295,7 @@ def parse_func(code, _globals, sigs, origcode, _vars={}):
     if not len(sig.args):
         copier = 'pass'
     elif sig.name == '__init__':
+        #Problem?
         copier = ['codecopy', RESERVED_MEMORY, '~codelen', copy_size]
     else:
         copier = ['calldatacopy', RESERVED_MEMORY, 4, copy_size]
@@ -315,6 +318,7 @@ def parse_func(code, _globals, sigs, origcode, _vars={}):
     if sig.name == '__init__':
         o = LLLnode.from_list(['seq'] + clampers + [parse_body(code.body, context)], pos=getpos(code))
     else:
+        #Problem?
         method_id_node = LLLnode.from_list(sig.method_id, pos=getpos(code), annotation='%s' % sig.name)
         o = LLLnode.from_list(['if',
                                   ['eq', ['mload', 0], method_id_node],
@@ -322,6 +326,7 @@ def parse_func(code, _globals, sigs, origcode, _vars={}):
                                ], typ=None, pos=getpos(code))
     o.context = context
     o.total_gas = o.gas + calc_mem_gas(o.context.next_mem)
+    #Problem?
     o.func_name = sig.name
     return o
```

**Comment by DavidKnott** [comment]
I don't think this is an issue because changing the `to_abi_dict` won't change the `FunctionSignature` itself (which is what's used in `parser.py`).  Why did you add the `sig` key?

**Comment by fubuloubu** [comment]
@DavidKnott just so the prior usage was available. It does not have to be there however. Adding a field to the ABI isn't itself dangerous, but I guess being inconsistent can be a problem.

**Comment by fubuloubu** [comment]
That's a fair point and probably why testing passes okay after I removed my change in the `from_definition()` function

**Comment by DavidKnott** [comment]
@fubuloubu I don't think `sig` should be kept because all it's doing is duplicating information.  Also, I'd like to get Viper's abi as close to Solidity's as possible so that integrating with development frameworks (primarily Populous) goes as smoothly as possible.

**Comment by fubuloubu** [comment]
Agreed, it's gone

**Comment by DavidKnott** [comment]
@fubuloubu Thanks a lot! LGTM.

**Pull request merged**
