### PR TITLE
Add the install instructions for the Viper snap

### PR DESCRIPTION
**Pull request by elopio**
This requiries #445, and enabling the continuous delivery on https://build.snapcraft.io

### - What I did

Added instructions to install the viper snap

### - How I did it

I fought a little with rst syntax :)

### - How to verify it

After #445 lands and the snap is published to the edge channel in the store, run the documented command.

### - Description for the changelog

Add the install instructions for the Viper snap

### - Cute Animal Picture

photo4949638119024601010

(I only have one cute animal, sorry)

### CODE REVIEW

**Comment by DavidKnott** [comment]
@elopio Why does `sudo` have to be used for the install?

**Comment by elopio** [comment]
@DavidKnott the snap is installed system-wide, and that has to be done by an admin.

**Comment by fubuloubu** [comment]
I don't think snapcraft does user installs yet. solc works this same way

**Comment by DavidKnott** [comment]
Makes sense, LGTM

**Comment by elopio** [comment]
Wait, but this hasn't been released to the store yet :) Can somebody from the viper team go to https://build.snapcraft.io/ to enable the automated build and release?

@fubuloubu are you using the solc snap? I would love to hear how is that working for you.

**Comment by fubuloubu** [comment]
Works fine lol. We haven't released to PyPI yet, so I don't think we had plans for snapcraft. @DavidKnott perhaps it is time for planning a stablish 0.1.0 release to serve as placeholders in this systems?

**Comment by DavidKnott** [comment]
@fubuloubu Yes!  I agree it's time 👍

**Comment by elopio** [comment]
Well, that's what's great about the snapcraft channels (note the obvious bias on my tone :) The edge channel is designed to follow pre-releases. The idea is that very unstable changes that are landing in master can be immediately tested. Your community of early adopters doesn't need to wait for a release to provide feedback.

But well, having said that, after smoke testing this for a while I agree that a 0.1 release sounds very nice.

If you make the release an [annotated tag](https://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags) the snap will use the tag as the version during the build.

**Comment by fubuloubu** [comment]
@elopio that means we can have an `edge` channel without a stable one?

**Comment by elopio** [comment]
@fubuloubu yes. https://build.snapcraft.io will trigger a build every time master changes, and put the resulting snap in edge. From there, you define your release pipeline however you want, with a combination of manual and automated tests to gate when to move to the beta, candidate or stable channels.

If you installed the solc snap from stable, then you will get it updated only when a maintainer moves a new revision to that channel. But if you do:

    sudo snap refresh solc --edge

You will get automatic updates multiple times every day.

**Comment by fubuloubu** [comment]
Automatic?? That's freaking sick. I didn't know snapcraft did auto behind the scenes?

As much as I love the `apt` package manager, I do miss the Windows manager that would just install automatically easy updates whenever you were online. If snapcraft enables that, color me excited!

**Comment by elopio** [comment]
welcome to the future of Linux distros! :)
We are still defining how that future will look, so any feedback or feature request you have for us will be very welcome. All the development discussions happen here in case you want to join: https://forum.snapcraft.io/

**Comment by fubuloubu** [comment]
Long-time Ubuntu user and a big fan of snapcraft. My only comment is keep up the awesome work!

**Comment by fubuloubu** [comment]
BTW @DavidKnott is the only one with admin rights for our repo, he'll have to go through the instructions to associate the repo. It works eight through GitHub!

**Comment by elopio** [comment]
Hey @DavidKnott @fubuloubu @jacqueswww, here at ubuntu we have a very popular blog with a lot of views: https://insights.ubuntu.com/
Yesterday I was talking with our PR manager about recent interesting stuff, and she said that it would be nice to get an interview about viper posted in there. It would be something like this: https://insights.ubuntu.com/2017/11/08/discovering-snaps-with-net-and-microsoft/

I think it would be great to sync that with your first 0.1 release, to get more early testers. Would you be interested?

**Comment by fubuloubu** [comment]
Sound sgreat to me! We're discussing a name change, so I think it would be best until after that

**Comment by elopio** [comment]
alright, whenever you are ready let us know and we'll do some marketing noise from here.

**Comment by jacqueswww** [comment]
@elopio We have renamed viper to vyper (it's a long story hehehe). In the process I see I renamed everything in the existing snap channel. How do I go about adding this repo to a new channel 'vyper' ?
I see more and more trouble for people getting the compiler going (because of py3.6), and it would be great if I could just recommend snap to them :)

**Comment by elopio** [comment]
hello @jacqueswww, sorry for the late reply.
I see that vyper was registered and released to edge by somebody named nuclearjoker:

```
$ snap info vyper
name:      vyper
summary:   Experimental language for the Ethereum Virtual Machine
publisher: nuclearjoker
license:   Proprietary
description: |
  Vyper is an experimental, contract-oriented, pythonic programming language
  that targets the Ethereum Virtual Machine (EVM)
snap-id:     vYiW6shppbw5xmGOhnxLSJSLbxElt7AF
channels:                      
  stable:    –                      
  candidate: –                      
  beta:      –                      
  edge:      0+git.df31e33 (1) 38MB devmode
```

Is that somebody from your team? I would love to see this one released to stable and highlighted on our social media, so let me know if you need something else from our side :)

**Comment by jacqueswww** [comment]
Hi elopio,

Yes that was me, hehe - I figured out how to it and is cool because we can eventually make the auto build happen this way. 

Will push a stable soon, when we tag the alpha release.

**Comment by jacqueswww** [comment]
Hi elopio,

Yes that was me, hehe - I figured out how to it and is cool because we can eventually make the auto build happen this way. 

Will push a stable soon, when we tag the alpha release.

**Pull request merged**
