### PR TITLE
Moving installation instructions to documentation

### PR DESCRIPTION
**Pull request by JackieXu**
### - What I did
I've moved the installation instructions that were in the original README file to the docs.
Also added some extra instructions, and reworded some things for simplicity.

Just another step into getting #291 resolved. Similar things to #336, but moves a different section.

### - How I did it
Moved things from README, and edited the text, and tried things using different operating systems.

### - How to verify it
Check out the pull request (it's my `docs-update` branch) and run a `make docs`.

### - Description for the changelog
Moved installation instructions and added information.

### - Cute Animal Picture
Yet another cute cat

### CODE REVIEW

**Comment by JackieXu** [comment]
Work in progress! I intend to test some stuff on a Windows machine today, to make sure I can fill in that section as well.

Additionally, I have a docker image that works, but it's currently a bit of a hassle to run it (same as the Solidity `solc` docker). It's currently registered under `jackiexu/viper`; I would rather have it under `ethereum/viper`, but I don't know what the process is to make that happen.

**Comment by DavidKnott** [comment]
@JackieXu I just merged the pull request from @fubuloubu, can you rebase from master and add the readthedocs installation link to the new readme?

**Comment by JackieXu** [comment]
Thanks, I've rebased on top of the updated master, and updated the PR. I've removed the Windows and Docker sections for now; didn't have a Windows dev machine at hand. Will try a VM later. Same for getting an easier to use Docker image.

**Comment by DavidKnott** [comment]
@JackieXu I looked it over and it looks good.  One thing, I don't think the links are working correctly (I'm seeing the actual url as opposed to the words with a link). 
I looked up the formatting for `readthedocs` and it's this:
    `virtualenv guide <https://virtualenv.pypa.io/en/stable/>`_
For further reference I'd look [here](https://raw.githubusercontent.com/ethereum/solidity/develop/docs/index.rst) at how the Solidity docs does it.

screen shot 2017-09-08 at 7 02 08 pm

**Comment by JackieXu** [comment]
Thanks for the look-over, @DavidKnott! I've updated it to use the correct hyperlink formatting. Apparently I've seen so many Markdown files, I'm starting to parse them subconsciously now.

**Comment by DavidKnott** [comment]
@JackieXu Thanks for making the changes, it looks good to me.

**Comment by DavidKnott** [comment]
Merging this in.

**Pull request merged**
