### PR TITLE
Add the packaging metadata to build the viper snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest viper in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery. That will release every change in the master branch to the edge channel in the store, were it can be tested by early adopters before releasing to the stable channel.

### - What I did

A snap package for viper.

### - How I did it

Addinng the metadata file and running the snapcraft command.

### - How to verify it

In Ubuntu 16.04 or later, call snapcraft on the root of this branch.

### - Description for the changelog

Add the packaging metadata to build the viper snap

### - Cute Animal Picture

photo4904470258664974293

### CODE REVIEW

**Comment by DavidKnott** [comment]
@elopio Thanks for adding this, excited to play around with it!

**Comment by elopio** [comment]
Thanks for reviewing @DavidKnott! Let me know if you have any questions.

**Comment by jacqueswww** [comment]
@elopio this looks great thanks, just tested the yaml file locally. Could you maybe add this details to the documentation on how to install it  (assuming it's on snapcraft.io:) )?

**Comment by elopio** [comment]
Thanks @jacqueswww! This will be awesome in the store!
I proposed the install instructions in #490.

**Pull request merged**
