### PR TITLE
Audit Findings

### PR DESCRIPTION
**Pull request by fubuloubu**
### - What I did

Implement @jacqueswww findings on gitter

### CODE REVIEW

**Comment by jacqueswww** [comment]
LGTM :)

**Comment by DavidKnott** [comment]
@fubuloubu Can you add a test for `sell_order` being negative as well?

**Comment by fubuloubu** [comment]
@DavidKnott added

**Comment by DavidKnott** [comment]
@fubuloubu Thanks a lot! LGTM

**Pull request merged**
