### PR TITLE
Add online compiler note to the README

### PR DESCRIPTION
**Pull request by holgerd77**

### CODE REVIEW

**Comment by DavidKnott** [comment]
@holgerd77 Could you also add this information to the rst docs?

**Comment by holgerd77** [comment]
Hmm, at the moment there is not really a section where this would fit in I suppose?

**Comment by DavidKnott** [comment]
I'd add a section to the front page, please see the Solidity docs page [here](https://solidity.readthedocs.io/en/develop/) as a reference.

**Comment by holgerd77** [comment]
Ok, done.

**Comment by DavidKnott** [comment]
@holgerd77 Thanks a lot for making the changes, I'm happy to merge this in.  Please try to keep the server as up to date as possible (viper's changing everyday).

**Comment by holgerd77** [comment]
@DavidKnott Can you add the direct link to the viper documentation as the main repository URL (so alongside the "New experimental programming language" header text) (so: https://eth-viper.readthedocs.io/en/latest/index.html).

Just hit me that I've never seen the front page of the docs cause the doc link in the "Installation" README section directly links into the installation chapter of the viper docs and that's what I always used as an entry point to the documentation.

**Comment by holgerd77** [comment]
It's also always good to use the (relatively) new GitHub topics feature and also add a few topics to the header, this helps a lot on discoverability on GitHub.

**Pull request merged**
