### PR TITLE
Change @internal decorator to @private decorator.

### PR DESCRIPTION
**Pull request by jacqueswww**
### - What I did

Implements https://github.com/ethereum/viper/issues/471.

### - How I did it

Was quite simple, just renamed internal in function_signature.py to private, and then replaced all other occurrences.

### - How to verify it
Compile something like:
```python

@private
def _add(a: num, b: num) -> num:
    return a + b


@public
def add(a: num, b: num) -> num:
    self._add(a, b)

```
And check/ttest the abi and contract output.

### CODE REVIEW

**Comment by fubuloubu** [comment]
Nice. You `grep`'d for all the uses right? I love grep

**Comment by jacqueswww** [comment]
@fubuloubu I did, looks good to me :smile_cat: 
image

**Comment by DavidKnott** [comment]
LGTM

**Comment by jacqueswww** [comment]
Cool, thanks :smile:

**Pull request merged**
