### PR TITLE
Fix wrong indentation in docs

### PR DESCRIPTION
**Pull request by adhikasp**
### - What I did

Indenting the warning blocks and move word around because its breaking 80 char limit.

### - How I did it

By... editing it?

### - How to verify it

See the rendered text. The `warning` is not separated like before.

### - Description for the changelog

Fix minor indentation problem in docs.

### - Cute Animal Picture

viper?

### CODE REVIEW

**Comment by DavidKnott** [comment]
@adhikasp I'm not too worried about the 80 char limit being broken in the docs, but can you change all `Notes` in `viper-by-example.rst` to be in the `Note` box (right now it cuts off after the first line)?

**Comment by adhikasp** [comment]
Of course, I haven't finish the tutorial so I doesn't notice the remainder 😄 
Anyway updated.

**Comment by DavidKnott** [comment]
@adhikasp I just opened the docs with your changes locally and the notes are still cut off after the first line, would you mind fixing that?

**Comment by adhikasp** [comment]
My bad, I fix it and now properly check it by building locally. All seems good.

**Pull request closed without merging**
