### PR TITLE
Format the ABI output to be JSON.

### PR DESCRIPTION
**Pull request by jacqueswww**
### - What I did

- For easy copy-paste purposes, I found that I constantly had to convert the python ABI output from the command line, this just does a simple json.dumps to make it easier.
- Minor pep8 fixes in the same file.

### - How I did it

Inserted a json.dumps ;)

### - How to verify it

Run `./viper_bin.py examples/crowdfund.vy -f json` and check the output.

### - Description for the changelog

Use JSON ABI output instead of python output (-f abi).

### CODE REVIEW

**Comment by fubuloubu** [comment]
I beileve we had decided on Python output for `abi`, but maybe you can add a forth formatting option for `json` instead? I have no problems with adding another format

**Comment by jacqueswww** [comment]
Ah I see, sure will do 😉

**Comment by jacqueswww** [comment]
@fubuloubu updated to add the `json`  option.

**Comment by fubuloubu** [comment]
Perfect, I like it!

**Comment by DavidKnott** [comment]
@jacqueswww Thanks a lot for doing this, LGTM

**Pull request merged**
