### PR TITLE
Added fixture for helping get logs

### PR DESCRIPTION
**Pull request by fubuloubu**
### - What I did

Added a fixture for testing logs

### - How to verify it

Use it. Let me know if there are problems

NOTE: @DavidKnott, I thought about re-arranging all the code in 'parser/features/test_logging.py' but then I realized you would want to test more of the internals in there. I believe this fixture should probably not be used there, but basically anywhere else logs are used.

### - Cute Animal Picture

> Hooray

### CODE REVIEW

**Comment by DavidKnott** [comment]
@fubuloubu I think not using the helper for `parser/features/test_logging.py` was a good call.  What do you think about making it so that the developer can get whatever log they want as opposed to only the most recent one?

**Comment by fubuloubu** [comment]
Well, for testing purposes you should be checking immediately after the log call was made. Although, I could see a scenario where two logs fire off, and now you can't access one. Maybe a slight modification where it just gets the last log available matching the name you're looking for?

**Comment by DavidKnott** [comment]
@fubuloubu Fair point, LGTM

**Comment by fubuloubu** [comment]
I'll keep this branch and think of some alternative ways that lets you get multiple logs, if desired (e.g. if you specify a log name, you get a list of logs with that name and do `logs[-1]` to get the last). If you don't specify a name, you get all logs, grouped by name (e.g. `logs = {'Log1' : [list...], 'Log2' : [list...], etc.]`)

**Pull request merged**
