### PR TITLE
Improve for loop error

### LINKED ISSUE #562: Failed to compile a for loop with a variable as a range() argument
This code compilation is failing with the next error message: _**"Repeat must have a nonzero positive integral number of rounds"**_.

`some_value = 4`
`for i in range(some_value):` 
`// do something`

The same situation is present if check that the value is grater than 0:

`some_value = 4`
`if some_value > 0:` 
`for i in range(some_value):` 
`// do something`

* viper Version: 0.0.2

### PR DESCRIPTION
**Pull request by DavidKnott**
### - What I did
Improve for loop error message. @khotkevych is is this error clearer?
Fixes #562 
### - How I did it
Looked at what caused the error and changed the error message to match it. 
### - How to verify it
Look at the error I changed.
### - Description for the changelog
None
### - Cute Animal Picture
image

### CODE REVIEW

**Comment by fubuloubu** [comment]
I think @khotkevych's example actually still satisfies what the error message says, but it doesn't compile (and I don't think it should). The error message should probably say something more like "range only accepts positive, non-zero integers as arguments"

**Comment by DavidKnott** [comment]
@fubuloubu It does satisfy the error message but the error that triggers the ones I changed is only when the number of iterations isn't fixed as different errors are triggered when `num_iterations <= 0`.

**Comment by fubuloubu** [comment]
Ah, maybe something like "range only accepts literal values"

**Comment by jacqueswww** [comment]
+1 for "range only accepts literal values"

**Comment by DavidKnott** [comment]
Changed it to "range only accepts literal values," merging it in.

**Pull request merged**
