### PR TITLE
Rename argument named function by func in `check_gas`

### PR DESCRIPTION
**Pull request by yograterol**
Renamed argument called `function` by `func`, in Python `function` is a built in name.

### CODE REVIEW

**Comment by fubuloubu** [comment]
No problems with this, although I wish there was a summary in the PR so I knew what the suggestion was (basically semantics/style updates)

**Comment by yograterol** [comment]
@fubuloubu you're right, I need to fix all tests to call the right argument. I'll add the summary.

**Comment by yograterol** [comment]
@vbuterin this PR is ready.

**Comment by DavidKnott** [comment]
@yograterol This looks good to me,  would you mind rebasing it?

**Comment by DavidKnott** [comment]
Closing this to due to PR #441

**Pull request closed without merging**
