### PR TITLE
Removed suicide keyword

### PR DESCRIPTION
**Pull request by fubuloubu**
### - What I did
Removed suicide per #548

### - How I did it
Grep magic

### - How to verify it
Tests fine!

### - Description for the changelog
Removed suicide keyword and opcode

### - Cute Animal Picture

Don't club baby seals

### CODE REVIEW

**Comment by fubuloubu** [comment]
Basically as a reminder that we made this decision? Could probably just modify one of the cases that checks for any unspecified function with a malformed keyword. I can do that, just trying to understand the utility.

**Comment by DavidKnott** [comment]
+1 Adding an invalid test with `sucide`, other then that LGTM

**Comment by fubuloubu** [comment]
Alright, here you go!

**Comment by DavidKnott** [comment]
@fubuloubu Thanks a lot, LGTM

**Pull request merged**
