### PR TITLE
Add init file to signatures folder

### PR DESCRIPTION
**Pull request by DavidKnott**
### - What I did
Add init file to `signatures` folder so the `viper` compile command works. This pr is in response to #367.  @msoedov Thanks for making an issue!
### - How I did it
Made an `init` file.
### - How to verify it
Look at my pr.
### - Description for the changelog
None
### - Cute Animal Picture
image

### CODE REVIEW

**Comment by msoedov** [comment]
@DavidKnott Hi

Small update, I actually installed it via
```shell
 pip install  git+git://github.com/ethereum/viper.git
``` 
and there is no subpackage called `signatures` in my local env
```shell
ls /Users/msoedov/pyenvs/workd/lib/python3.6/site-packages/viper
__init__.py           compiler.py           functions.py          parser.py             utils.py
__pycache__           exceptions.py         opcodes.py            parser_utils.py
compile_lll.py        function_signature.py optimizer.py          types.py
```

I guess it's either some weird quirk of setup py package discovery or pip installation issues
```shell
pip --version
pip 9.0.1 from /Users/msoedov/pyenvs/workd/lib/python3.6/site-packages (python 3.6)
```

**Comment by DavidKnott** [comment]
Hmm, that's really stranger.  I'll try looking into it more.

**Comment by msoedov** [comment]
I don't have a good explanation myself, got the same issue on another laptop

**Comment by pdaian** [comment]
0fb8ecb6a51314d64b392aa5947a042d3cd58312 solved this on my machine

**Comment by DavidKnott** [comment]
@pdaian Thanks for the update, closing this PR.

**Pull request closed without merging**
