### PR TITLE
Check for missing return statement

### PR DESCRIPTION
**Pull request by jacqueswww**
### - What I did

Partial fix for #590.
Check for a minimum of 1 return statement if specified.

### - How I did it
Added a count in the function context.

### - How to verify it
```python
@public
def foo() -> num:
        pass
```

### CODE REVIEW

**Comment by fubuloubu** [comment]
LGTM for now, obviously will have to rewrite it when we do the branching check instead.

Actually, can you add a TODO note to that effect in the parser code?

**Comment by DavidKnott** [comment]
Looks like a good first step, particularly because making sure every endpoint has the correct return is significantly more logic.  I'd love to see a test or two with conditional returns to make the limits of this fix clearer.

**Comment by DavidKnott** [comment]
LGTM, merging it in.

**Comment by fubuloubu** [comment]
Since we have the correct algorithm in #590 according to @yzhang90, perhaps we can upgrade the check now?

**Pull request merged**
