### PR TITLE
If in a list support

### PR DESCRIPTION
**Pull request by jacqueswww**
### - What I did
Implements #428, we can now use `x in [1, 2, 3, 4]` syntax :smiley_cat: 

### - How I did it

- Added handling for the specific case in expr.py/Expr.compare function.

### - How to verify it
Check tests, and write some code:

```python
allowed: num[10]


def set():
    self.allowed = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


def in_test(x: num) -> bool:
    if x in self.allowed:
            return True
    return False
```

### CODE REVIEW

**Comment by fubuloubu** [comment]
@DavidKnott Just checking, `list` types can only contain 1 type of element, right?

@jacqueswww I don't think the updated parser code checks that the type of the left hand side of the operation matches the containing type of the list. Needs a test to that effect at least.

**Comment by fubuloubu** [comment]
Otherwise, nice job!

**Comment by DavidKnott** [comment]
@fubuloubu I think lists only containing 1 data type makes the most sense.  It'd get messy/confusing really fast with multiple types.

**Comment by fubuloubu** [comment]
Oh, I wasn't suggesting otherwise. Just confirming that assumption with you ;)

**Comment by DavidKnott** [comment]
@jacqueswww Could you add some tests with different data types?

**Comment by jacqueswww** [comment]
Will do :smile_cat:

**Comment by jacqueswww** [comment]
@DavidKnott added a specific exception message ;)

**Comment by DavidKnott** [comment]
@jacqueswww Thanks a lot, if I'm understanding correctly this pr is only meant to support checking for `num`'s in lists?

**Comment by jacqueswww** [comment]
Yes, only numeric base32 types.

**Pull request merged**
